### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [sildur/offline_geocoder#2]
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [x] It's tested
- [ ] It's hooked to a the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT)
- [ ] It has a link to the [open-source hipchat room](https://www.hipchat.com/gpBpW3SsT) in its README
- [ ] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page
## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks
- [ ] It's shared on reddit
- [ ] It's shared on hacker news with a title like Show HN: description
- [ ] It has a landing page built in github pages
## For Libraries
- [x] Examples of use are documented in the README or linked from there
## For Ruby Projects
- [ ] It's checked with [Hound](https://houndci.com)
- [x] It's _gemified_
